name: Shell Script Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Run shellcheck
      run: |
        # Run shellcheck on all shell scripts
        find . -type f -name "*.sh" -exec shellcheck {} +
        # Also check the bats test files
        find . -type f -name "*.bats" -exec shellcheck {} +

    - name: Install bats
      if: success()  # Only run if shellcheck passed
      run: sudo apt-get install -y bats

    - name: Run bats tests
      if: success()  # Only run if previous steps passed
      env:
        DRY_RUN: true  # Force dry run mode
        GITHUB_TOKEN: ""  # Prevent accidental GitHub API calls
      run: bats test/*.bats

    - name: Report test results
      if: always()  # Run even if tests fail
      run: |
        echo "Shellcheck status: ${{ job.status }}"
        if [ "${{ job.status }}" = "success" ]; then
          echo "✅ All tests passed successfully!"
        else
          echo "❌ Tests failed. Please check the logs above."
        fi
